#!/usr/bin/env sh

usage ()
{
    cat <<_END
Usage: ${0} {options}
    where {options} include:
    -s, --service
        The name of the service to up
    -f, --foreground
        Up in the foreground
_END
    test -n "${*}" && echo "${*}"
    exit 99
}

append ()
{
    eval "${1}=\"\${${1}} ${2}\""
}

resolve_service ()
{
    case "${1}" in
        access|pa)
            echo pingaccess
            ;;
        directory|pd|ds)
            echo pingdirectory
            ;;
        directoryproxy|proxy|pdp|px)
            echo pingdirectoryproxy
            ;;
        dataconsole|console|pdc|dc)
            echo pingdataconsole
            ;;
        datasync|sync|pds)
            echo pingdatasync
            ;;
        datagovernance|datagov|pdg|dg)
            echo pingdatagovernance
            ;;
        datagovernancepap|pap)
            echo pingdatagovernancepap
            ;;
        delegator)
            echo pingdelegator
            ;;
        central|pc)
            echo pingcentral
            ;;
        federate|pf)
            echo pingfederate
            ;;
        *)
            echo ${1}
            ;;
    esac
}

_mode="-d"
_services=""
while ! test -z "${1}" ;
do
    case "${1}" in
        -s|--service)
            shift
            test -z "${1}" && usage "You must provide a service name"
            _service=$( resolve_service "${1}" )
            append _services "${_service}"
            ;;
        -f|--foreground)
            _mode=""
            ;;
        *)
            usage "unrecognized option"
            ;;
    esac
    shift
done

export TAG=$( docker images | awk '/pingbase/{print $2}' )

docker-compose up ${_mode} ${_services}
if test ${?} -ne 0
then
    echo "Could not up ${_services}"
else
    test -n "${_mode}" && docker-compose logs -f ${_services}
fi
